global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using MoBro.Plugin.SDK;
global using MoBro.Plugin.SDK.Builders;
global using MoBro.Plugin.SDK.Enums;
global using MoBro.Plugin.SDK.Models.Metrics;
global using MoBro.Plugin.Aida64.SharedMemory;